Make sure that jquery is imported from the correct path
maykinmedia/django-exportdb pull request #4
Opened 2016-06-13 11:02 UTC by eodolphi

Also make sure it is not included twice on the same page

2016-06-13 11:07 UTC, sergei-maertens commented
Is the jquery already in the `vendor` folder on Django 1.8? Looks allright for Django 1.9

2016-06-13 11:22 UTC, eodolphi commented
What is the minimal version this needs to be compatible with?

2016-06-13 11:22 UTC, sergei-maertens commented
1.8 - same as official django maintained versions
On Jun 13, 2016 13:22, "eodolphi" <notifications@github.com> wrote:

> What is the minimal version this needs to be compatible with?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/maykinmedia/django-exportdb/pull/4#issuecomment-225554385>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFQ01luKVTIxwiRY6hPJyHTzFCcPBeO4ks5qLT1ZgaJpZM4I0N2v>
> .
>

2016-10-05 12:33 UTC, eodolphi commented
Hi Sergei,

I updated the pull request so that the code is now also compatible with django < 1.9

And I added some changes for 1.10 compatibility.

2016-10-05 12:35 UTC, sergei-maertens commented
Hi @eodolphi, thanks, I was just looking at this because of mail notifications.

Question - do you still need < 1.8 support? If it's no longer required for you, we can use this PR to drop support for < Django 1.8, as I expect some of those builds to fail now because of some changes. 1.8, 1.9, 1.10 should be sufficient, unless you aren't on any of those versions yet ofcourse.

2016-10-05 12:38 UTC, eodolphi commented
I do not personally need support for < 1.9

Locally the tests pass on 1.8, 1.9 and 1.10, so I guess they should pass here too.

But I do not mind removing support for 1.8

2016-10-05 12:39 UTC, sergei-maertens requested changes
some small remarks w/r to DRY and separation of compatibility code

2016-10-05 12:39 UTC, sergei-maertens commented on exportdb/views.py
> +        context['jquery_in_vendor'] = (parse_version(django.get_version()) >= parse_version('1.9.0'))
it's generally nicer to put all the Django-version specific stuff in a `compat.py` file and import from there. Can you move this check/function to such a module?

2016-10-05 12:39 UTC, sergei-maertens commented on exportdb/views.py
> +        context['jquery_in_vendor'] = (parse_version(django.get_version()) >= parse_version('1.9.0'))
you can also simplify the version check, since `django.VERSION` is a tuple, you can do `if django.VERSION < (1, 9, 0)`

2016-10-05 12:39 UTC, sergei-maertens commented on tests/app/tests/test_views.py
> +        if parse_version(django.get_version()) >= parse_version('1.9.0'):
should use the function to-be-moved-into `compat.py`

2016-10-05 12:52 UTC, sergei-maertens commented
Travis build is failing because of missing environment in `tox.ini`:

(note that the djangoXY labels were not correct either)
```diff
- envlist = py{27,34,35}-django{1.6,1.7,1.8,1.9}
+ envlist = py{27,34,35}-django{16,.7,18,19,110}
```

and add to `deps` section in `tox.ini`:

```diff
+ django110: Django>=1.10,<1.11
```

2016-10-05 12:52 UTC, eodolphi commented
I do not fully understand the github review flow. I did the changes requested. Is there any other way besides this message to inform you of that?

2016-10-05 12:53 UTC, sergei-maertens commented
@eodolphi no, I think it only gets resolved when I click the 'approve changes' link, which I'll do now ;)

2016-10-05 12:53 UTC, sergei-maertens approved these changes

2016-10-05 12:54 UTC, sergei-maertens commented
I'll take care of the incorrect labeling in `tox.ini`, merging now and uploading a version to PyPI in a minute.

2016-10-05 12:55 UTC, merged

2016-10-05 12:56 UTC, eodolphi commented
Thanks!

2016-10-05 12:59 UTC, sergei-maertens commented
0.4.7 is now on PyPI